name: Dotnet NUnit test

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      # ~~~~~~~~~~~~~ .Net setup ~~~~~~~~~~~~~
      - name: Set up dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build

        # ~~~~~~~~~~~~~ Run ~~~~~~~~~~~~~
      - name: Run and compute coverage
        run: |
          ./get_coverage_for_challenge.sh TST
          grep "50" ./coverage.tdl
